[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "advisory_lock"
version = "1!0.0.1788850242"
description = "Context manager for fcntl advisory locks"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
]
license = "ISC"
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/jakeogh/advisory-lock"

[project.scripts]
advisory-lock = "advisory_lock.advisory_lock:cli"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
advisory_lock = [
    "py.typed",
]
